(include_subdirs unqualified)

(library
 ; (modules :standard \ Warmup)
 (name tylr_core)
 (virtual_modules sort grammar)
 (libraries stds sedlex re sexplib uutf fmt)
 (js_of_ocaml)
 (preprocess
  (pps
   ppx_let
   ppx_blob
   ppx_sexp_conv
   ppx_yojson_conv
   ppx_deriving.show
   ppx_deriving.ord
   ppx_deriving_hash
   sedlex.ppx))
 (preprocessor_deps
  (file material/precompiled/stances.txt)
  (file material/precompiled/nts.txt)
  (file material/precompiled/walk_r_map.txt)
  (file material/precompiled/walk_l_map.txt)
  (file material/precompiled/enter_r_map.txt)
  (file material/precompiled/enter_l_map.txt)))

(env
 (dev
  (js_of_ocaml
   (flags :standard --debuginfo --noinline --dynlink --linkall --sourcemap)))
 (release
  (js_of_ocaml
   (flags :standard))))
